## Домашнее задание «Функции и работа с данными»

### Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [133]:
import pandas as pd
movies_rt = pd.read_csv('ml-latest-small/ratings.csv')
def rating_level(row):
    rt_class = ''
    if row  <= 2:
        rt_class = 'низкий рейтинг'
    if row  > 2 and row <= 4:
        rt_class = 'средний рейтинг'
    if row  > 4 and row <= 5:
        rt_class = 'высокий рейтинг'
    return rt_class
movies_rt['class'] = movies_rt['rating'].apply(rating_level)
movies_rt.loc[15:25]

    userId  movieId  rating   timestamp            class
15       1     2193     2.0  1260759198   низкий рейтинг
16       1     2294     2.0  1260759108   низкий рейтинг
17       1     2455     2.5  1260759113  средний рейтинг
18       1     2968     1.0  1260759200   низкий рейтинг
19       1     3671     3.0  1260759117  средний рейтинг
20       2       10     4.0   835355493  средний рейтинг
21       2       17     5.0   835355681  высокий рейтинг
22       2       39     5.0   835355604  высокий рейтинг
23       2       47     4.0   835355552  средний рейтинг
24       2       50     4.0   835355586  средний рейтинг
25       2       52     3.0   835356031  средний рейтинг

In [134]:
movies_rt['class'].value_counts(),

(средний рейтинг    63801
 высокий рейтинг    22818
 низкий рейтинг     13385
 Name: class, dtype: int64,)

### Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

> geo_data = {

> 'Центр': ['москва', 'тула', 'ярославль'],

> 'Северо-Запад': ['петербург', 'псков', 'мурманск'],

> 'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [156]:
geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск'] }
keywords = pd.read_csv('ml-latest-small/keywords.csv')
def region_definer(row):
    region = ''
    for region_list in geo_data.items():
        for city in region_list[1]:
            if city in row :
                region = region_list[0]
    if not region:
        region = 'undefined'
    return region
keywords['region'] = keywords.keyword.apply(region_definer)
print (keywords.groupby('region').count().head())
keywords.loc[15:25]

                keyword  shows
region
undefined         99253  99253
Дальний Восток       94     94
Северо-Запад        268    268
Центр               385    385

                          keyword    shows     region
15                           секс  5431732  undefined
16                           гугл  5175471  undefined
17                             dr  4880955  undefined
18                    алиэкспресс  4879645  undefined
19                        рамблер  4540421  undefined
20                    фильмы 2016  4486635  undefined
21                         погода  4344510  undefined
22                             vk  4330448  undefined
23              ютуб видеохостинг  4215267  undefined
24                          дойки  4133424  undefined
25  одноклассники социальная сеть  4018230  undefined

In [142]:
keywords.region.value_counts()

undefined         99253
Центр               385
Северо-Запад        268
Дальний Восток       94
Name: region, dtype: int64